eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_LIST:localhost:8761}/eureka/
server:
  port: 9122
spring:
  application:
    name: service-feign

#feign:
#  hystrix:
#   enabled: false