eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_LIST:localhost:8761}/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      username: xxxx
      version: v1.0
      tag: dev
      serviceCatalog: 人工智能
      serviceVerison: v1.0
      serviceStatus: 未发布
      serviceProvider: DBP
      serviceDescription: 无
      serviceConfigureURL: 无



#以后的服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: service1-hi
server:
  port: 9001
management:
  security:
    enabled: false

info:
  version: "@project.version@"



