server:
  port: 9002
spring:
  application:
    name: gray-service
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      gated-launch: false
      service-version: 0.1
      UserId: xxxxxxxxxxxx


info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
  contact:
    email: jq.deng@hnair.com
    phone: 13888888888