
spring:
  application:
    name: consumer1
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          auto-create-topics: true
      bindings:
        input:
          destination: stream-demo
          content-type: text/plain
        output:
          destination: stream-demo-trans


server:
  port: 8082
