

spring:
  application:
    name: consumer2
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          auto-create-topics: true
      bindings:
        MyInput:
          destination: stream-demo
          content-type: text/plain



server:
  port: 8083
