spring:
  application:
    name: turbine-server
server:
  port: 8769
security:
  basic:
    enabled: false
turbine:
  aggregator:
    cluster-config: default
  app-config: service-hi
  clusterNameExpression: new String("default")
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


